spring.application.name=examen


spring.datasource.url=jdbc:postgresql://localhost:5432/eventplanner
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver