spring.application.name=examen
spring.datasource.url=jdbc:postgresql://localhost:5432/eventplanner
spring.datasource.username=postgres
spring.datasource.password=adgjmptxw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
