spring.application.name=examen
spring.datasource.url=jdbc:postgresql://localhost:5432/EventPlanner
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver
